### ISSUE TITLE
Hydra Issue 

### ISSUE THREAD

**Issue by asudeeaydin** [IIT-PAVIS/event_library#1]
I'm trying to generate the Human3.6m Events dataset, from your 'Lifting Monocular Events to 3D Human Poses' paper. 

When I ran:
```
python3 event_library/tools/generate.py frames_dir=/longtermdatasets/asude/human3.6m_downloader/training/subject/S1/Videos/ output_dir=/longtermdatasets/asude/h36m_events/S1/ upsample=true emulate=true search=false representation=raw
```

I got the following error, does this seem familiar to you, do you know a fix? 
```
event_library/tools/generate.py:102: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="confs", config_name="generate.yaml")
/home/asude/evgen/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'generate.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/asude/evgen/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:415: UserWarning: In generate.yaml: Invalid overriding of hydra/help:
Default list overrides requires 'override' keyword.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/defaults_list_override for more information.

  deprecation_warning(msg)
/home/asude/evgen/lib/python3.8/site-packages/hydra/core/default_element.py:124: UserWarning: In 'vid2e/standard': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/asude/evgen/lib/python3.8/site-packages/hydra/core/default_element.py:124: UserWarning: In 'representation/raw': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/asude/evgen/lib/python3.8/site-packages/hydra/core/default_element.py:124: UserWarning: In 'hydra/help/generate': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/asude/evgen/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[2023-01-27 12:09:18,639][__main__][INFO] - representation:
  type: raw
  args: null
vid2e:
  _target_: event_library.generator.SimulatorWrapper
  params:
    Cp: 0.2
    Cn: 0.2
    refractory_period: 0.0001
    log_eps: 0.001
    use_log: true
    batch_size: 30000
input_dir: null
frames_dir: /longtermdatasets/asude/human3.6m_downloader/training/subject/S1/Videos/
upsample_dir: null
tmp_dir: ${output_dir}/tmp
output_dir: /longtermdatasets/asude/h36m_events/S1/
hw_type: dvs
search: false
upsample: true
emulate: true

[2023-01-27 12:09:18,639][__main__][INFO] - HardwareProperties(size=(346, 260))
[2023-01-27 12:09:18,639][__main__][INFO] - Upsampling
Downloading SuperSlowMo checkpoint to /home/asude/evgen/lib/python3.8/site-packages/esim_py_upsampling/models/SuperSloMo.ckpt ...
HTTP Error 404: Not Found
MODEL not found. Please provide it manually
Upsampling failed, but directory '/longtermdatasets/asude/h36m_events/S1//tmp/upsample' was created. Remove it if you need to try again 
[2023-01-27 12:09:18,682][__main__][INFO] - Upsampling completed
Error executing job with overrides: ['frames_dir=/longtermdatasets/asude/human3.6m_downloader/training/subject/S1/Videos/', 'output_dir=/longtermdatasets/asude/h36m_events/S1/', 'upsample=true', 'emulate=true', 'search=false', 'representation=raw']
Error in call to target 'event_library.generator.simulator.SimulatorWrapper':
TypeError("__init__() missing 5 required positional arguments: 'Cp', 'Cn', 'refractory_period', 'log_eps', and 'use_log'")
full_key: vid2e

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by asudeeaydin** [comment]
I've also tried running it in the docker container you provided and got a different Hydra error this time: 

```
/home/user/miniconda/lib/python3.8/site-packages/omegaconf/omegaconf.py:572: UserWarning: update() merge flag is is not specified, defaulting to False.
For more details, see https://github.com/omry/omegaconf/issues/367
  warnings.warn(
[2023-01-28 19:07:30,051][__main__][INFO] - input_dir: null
frames_dir: /home/s1data/Videos
upsample_dir: null
tmp_dir: ${output_dir}/tmp
output_dir: /home/event-based-hpe/event_library/tmp
hw_type: dvs
search: false
upsample: true
emulate: true
representation:
  type: raw
  args: null
vid2e:
  _target_: event_library.generator.SimulatorWrapper
  params:
    Cp: 0.2
    Cn: 0.2
    refractory_period: 0.0001
    log_eps: 0.001
    use_log: true
    batch_size: 30000

[2023-01-28 19:07:30,052][__main__][INFO] - HardwareProperties(size=(346, 260))
[2023-01-28 19:07:30,052][__main__][INFO] - Upsampling
Downloading SuperSlowMo checkpoint to /home/user/miniconda/lib/python3.8/site-packages/esim_py_upsampling/models/SuperSloMo.ckpt ...
HTTP Error 404: Not Found
MODEL not found. Please provide it manually
Upsampling failed, but directory '/home/event-based-hpe/event_library/tmp/tmp/upsample' was created. Remove it if you need to try again 
[2023-01-28 19:07:30,113][__main__][INFO] - Upsampling completed
Traceback (most recent call last):
  File "/home/user/miniconda/lib/python3.8/site-packages/hydra/utils.py", line 29, in call
    cls = _get_cls_name(config)
  File "/home/user/miniconda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 489, in _get_cls_name
    raise ValueError("Input config does not have a cls field")
ValueError: Input config does not have a cls field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "event_library/tools/generate.py", line 139, in <module>
    main()
  File "/home/user/miniconda/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    run_hydra(
  File "/home/user/miniconda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 252, in run_hydra
    run_and_report(
  File "/home/user/miniconda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 185, in run_and_report
    func()
  File "/home/user/miniconda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 253, in <lambda>
    lambda: hydra.run(
  File "/home/user/miniconda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 110, in run
    return run_job(
  File "/home/user/miniconda/lib/python3.8/site-packages/hydra/core/utils.py", line 107, in run_job
    ret.return_value = task_function(task_cfg)
  File "event_library/tools/generate.py", line 135, in main
    _do_simulation(cfg, tmp_upsample_dir, base_output_dir)
  File "event_library/tools/generate.py", line 30, in _do_simulation
    simulator = hydra.utils.instantiate(cfg.vid2e)
  File "/home/user/miniconda/lib/python3.8/site-packages/hydra/utils.py", line 37, in call
    log.error(f"Error instantiating '{cls}' : {e}")
UnboundLocalError: local variable 'cls' referenced before assignment
```

**Comment by gianscarpe** [comment]
Hi @asudeeaydin, sorry for the delay. Can you try with hydra==1.0.0? The issue is related to a newer hydra version

**Comment by asudeeaydin** [comment]
Thank you for the reply. I've installed hydra==1.0.0 but I'm getting a different error now. 

```
[2023-02-09 20:24:12,640][__main__][INFO] - input_dir: /longtermdatasets/asude/lifting_dataset
frames_dir: null
upsample_dir: null
tmp_dir: ${output_dir}/tmp
output_dir: /longtermdatasets/asude/lifting_dataset_events
hw_type: dvs
search: false
upsample: true
emulate: true
representation:
  type: raw
  args: null
vid2e:
  _target_: event_library.generator.SimulatorWrapper
  params:
    Cp: 0.2
    Cn: 0.2
    refractory_period: 0.0001
    log_eps: 0.001
    use_log: true
    batch_size: 30000

[2023-02-09 20:24:12,640][__main__][INFO] - HardwareProperties(size=(346, 260))
[2023-02-09 20:24:12,640][__main__][INFO] - Upsampling
The input directory must exist
Upsampling failed, but directory '/longtermdatasets/asude/lifting_dataset_events/tmp/upsample' was created. Remove it if you need to try again 
[2023-02-09 20:24:12,640][__main__][INFO] - Upsampling completed
/home/asude/lift/lib/python3.8/site-packages/hydra/_internal/utils.py:586: UserWarning: 
Field 'params' is deprecated since Hydra 1.0 and will be removed in Hydra 1.1.
Inline the content of params directly at the containing node.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/object_instantiation_changes
  warnings.warn(category=UserWarning, message=msg)
0it [00:00, ?it/s]
[2023-02-09 20:24:12,647][__main__][INFO] - Simulation end
```

I have omegaconf version 2.0.1 and hydra-core version 1.0.0.
